apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdCluster
metadata:
  name: etcdcluster-sample
spec:
  replicas: 3
  image: quay.io/coreos/etcd:v3.3.13
  selector:
    matchLabels:
      cluster: etcdcluster-sample
